apiVersion: v1
kind: Pod
metadata:
  name: sglang-yusheng
spec:
  tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: sglang
    image: lmsysorg/sglang:dev-cu13
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    - |
      mkdir -p /home/radixark/yushengsu /root/.ssh /run/sshd
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCnrs1dqiMWGrhugvzdxb3MSVcpyXhU1gMDRx2/AsgVJUvxOkZuTl2W7PyDi6VFujcaQzpDjvidVWCIevt+uHotA6JUtSpsWjdJ6VawSIYKmS96DBtDyPdyu3yNDsF0FzWsS5Co3TQuidhNqP0xoveGCudqP9x2cIJI90MYKnC0NHUkEf9Q66S/86IRrNWQw1Wd+hC+V3G4eXSuci+4hL0uaBleeZBiIPPw1haKbbSmMtTjxmxmJLE4SOfzCbpLUfgo72FN6kGpxXFcQx5MXDxJsKs8AHnes8V0P1sNIpvWiDiq8nDYraBoCWu9UnsIXYpS5H9YQRyLaqde7Z8qzkQRFwq6ZQSa2dx9+QXq8e9Ky31qI+AgQJZEQg56L6ft7hUiN5XWRY7yzUNIkLS7R2Wx0GxV+fm2z+JbJfelagYhU9/GU2FHLBFN1MYJGUJScfk9sYUQekbk323hgeOSvTnwAvlkF6bCdXE6W9XdPRlhy/fQsfdiPBLIYx184wFTGU= amd\yushensu@XSJYUSHENSU01' > /root/.ssh/authorized_keys
      chmod 700 /root/.ssh
      chmod 600 /root/.ssh/authorized_keys
      echo 'export PATH=$PATH:/usr/local/nvidia/bin:/usr/local/cuda/bin' >> /root/.bashrc
      echo 'export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:$LD_LIBRARY_PATH' >> /root/.bashrc
      ssh-keygen -A
      echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
      /usr/sbin/sshd
      sleep infinity
    env:
    - name: PATH
      value: "/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - name: LD_LIBRARY_PATH
      value: "/usr/local/nvidia/lib64"
    resources:
      requests:
        memory: "512Gi"
        cpu: "32"
        ephemeral-storage: "800Gi"
      limits:
        nvidia.com/gpu: 4
        memory: "850Gi"
        cpu: "64"
        ephemeral-storage: "1500Gi"
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 128Gi
